### ISSUE TITLE
One question about code implementation of learning rate

### ISSUE THREAD

**Issue by jz9888** [lx10077/fedavgpy#3]
In paper "On the convergence  of FedAvg on non-iid data", the learning rate _eta = eta0/(t+1)_, where _t_ means the current number of iterations (including local iterations and communication rounds).

Additionally, in your code in src/models/worker.py, I understand that `for epoch in range(self.num_epoch):` where _num_epoch_ refers to _E_ in the paper.

However, in your introdunction in github,
`python main.py --gpu --dataset $DATASET --clients_per_round $K --num_round $T --num_epoch $E --batch_size $B --lr $LR --device $device --seed $SEED --model $NET --algo $ALGO  --noaverage --noprint` where _num_round_ refers to _T_ and it is the thing that I cannot understand.

We could see the function `local_train` from your code in src/trainers/fedavg.py,
![image](https://user-images.githubusercontent.com/38000369/115348969-dcdd3780-a1e5-11eb-97db-c96b6b5b8d41.png)

I think _num_round_ in your code is not _T_. Instead, it refers to _T/E_. Therefore, I think there are some revisions to make.

**Comment by NookLook2014** [comment]
It seems that the lr remains the same during each local updation, the lr decays with  T/E (num_round) ?

**Comment by lx10077** [comment]
Yes. The lr remains the same during a round. It of course can be reduced at
each iteration. However, the decay rate should be carefully tuned,
otherwise, it would converge too slowly or quickly without desired accuracy.

Joey Lu ***@***.***> 于2021年8月17日周二 上午10:50写道：
